Add multiple sku code.
agungsuprayitno/vue-starter-kit pull request #24
Opened 2018-11-29 07:11 UTC by agungsuprayitno

2018-11-30 04:11 UTC, kendychow requested changes

2018-11-30 04:11 UTC, kendychow commented on src/views/voucher-order/VoucherOrderForm.vue
> +            <div class="col-12 my-2">If active status set to "Yes", the voucher will be generated with the secret code</div>
@agungsuprayitno dipindah ke description b-form-group aja :)

2018-11-30 07:07 UTC, agungsuprayitno commented on src/views/voucher-order/VoucherOrderForm.vue
> +            <div class="col-12 my-2">If active status set to "Yes", the voucher will be generated with the secret code</div>
udah di move ke form ya.

2018-12-03 05:03 UTC, kendychow approved these changes

2018-12-03 05:04 UTC, merged